# Changes here will be overwritten by Copier
_commit: v0.0.2
_src_path: gh:ninanor/python-template
author_name: ninanor
debug: false
default_branch_name: main
docker: false
email: taheera.ahmed@nina.no
project_name: Nedbygging project
project_slug: nedbygging_project
repo_name: nedbygging_project
repo_org: ninanor
template_type: python
type_annotations: false
