# TRAINING DATA
ROOT_PATH: /home/taheera.ahmed/data/nedbygging/
OUTPUT_PATH: /home/taheera.ahmed/data/nedbygging/pred_masks

CHECKPOINT_PATH: /home/taheera.ahmed/code/nedbygging-project/outputs/not-test/05 clahe whole/lightning_logs/version_0/checkpoints/epoch=32-step=132.ckpt
